# Generated by Django 2.1.1 on 2018-09-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20180909_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
    ]
